Repository Berlevog/yandex.middlefrontend.mario, pull requests merged in 2021-09, with the labels that each got.

#4 npm init
  package.json
Labels: good first issue

#6 02-init-react-prodject
  .babelrc
  .eslintrc.js
  .gitignore
  .mocharc.json
  .prettierignore
  .prettierrc.json
  .stylelintignore
  .stylelintrc.json
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  tsconfig.json
  webpack.config.js
Labels: good first issue

#7 добавил router
  src/App.tsx
  src/index.tsx
  src/pages/Login/Login.test.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/index.ts
  src/pages/Registration/Registration.test.tsx
  src/pages/Registration/Registration.tsx
  src/pages/Registration/index.ts
  src/pages/index.ts
  webpack.config.js
Labels: enhancement

#14 01 game engine
  .babelrc
  .eslintrc.js
  .husky/pre-commit
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.test.tsx
  src/App.tsx
  src/engine/CanvasComponent.tsx
  src/index.css
  src/index.tsx
  src/pages/Game/Game.tsx
  src/pages/Game/index.ts
  src/pages/Login/Login.tsx
  src/pages/Login/index.ts
  src/pages/Registration/Registration.tsx
  src/pages/Registration/index.ts
  src/pages/index.ts
  webpack.config.js
Labels: enhancement

#21 Добавил предохранитель и обернул в него <App />
  public/images/error-mushroom.png
  src/components/ErrorHandler/ErrorHandler.tsx
  src/components/ErrorHandler/index.ts
  src/index.tsx
Labels: enhancement

#20 карта
  .babelrc
  package-lock.json
  package.json
  public/images/cloud.png
  public/images/world.png
  public/music/world01.ogg
  src/engine/Application.tsx
  src/engine/Clouds.ts
  src/engine/Engine.test.ts
  src/engine/Engine.ts
  src/engine/PhysicalObject.ts
  src/engine/Player.ts
  src/engine/World.ts
  src/pages/Game/Game.tsx
  webpack.config.js
  webpack.copy_public.plugin.js
Labels: enhancement

#24 Login / Registration
  package-lock.json
  package.json
  public/assets/mario-background.jpeg
  public/index.html
  src/App.tsx
  src/constants/url.ts
  src/constants/validationErrors.ts
  src/constants/validationSchema.ts
  src/index.css
  src/pages/Login/Login.tsx
  src/pages/Profile/Profile.test.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Profile/index.ts
  src/pages/Registration/Registration.tsx
  src/pages/index.ts
  src/services/auth.ts
Labels: enhancement

#22 11 game start end
  public/images/frog.png
  public/images/game-end.png
  public/images/game-start.png
  src/pages/Game/Game.tsx
  src/pages/Game/components/End/End.tsx
  src/pages/Game/components/End/index.ts
  src/pages/Game/components/Start/Start.tsx
  src/pages/Game/components/Start/index.ts
  src/pages/Game/mockData.ts
Labels: enhancement

#25 Мелкие правки перед ревью
  package-lock.json
  public/music/game-over.ogg
  public/music/killed.ogg
  src/App.tsx
  src/engine/Player.ts
  src/engine/World.ts
  src/pages/Game/Game.tsx
  src/pages/Game/GamePages.tsx
  src/pages/Game/components/End/End.tsx
  src/pages/Game/components/Start/Start.tsx
  src/pages/Game/index.ts
  src/pages/Login/Login.tsx
  src/pages/Registration/Registration.tsx
Labels: hotfix
